const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v?new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'待核验';
const num=v=>v===null||v===undefined?'未覆盖':Number(v).toLocaleString('zh-CN');
const percent=v=>Number.isFinite(v)?Math.min(100,Math.max(0,v)):0;
const ring=(v,label)=>`<svg class="evidence-ring" viewBox="0 0 120 120" role="img" aria-label="${esc(label)} ${v}%"><circle class="ring-track" cx="60" cy="60" r="50"/><circle class="ring-value" opacity="${v===0?0:1}" cx="60" cy="60" r="50" pathLength="100" stroke-dasharray="${percent(v)} 100" transform="rotate(-90 60 60)"/><text x="60" y="66" text-anchor="middle">${v}%</text></svg>`;
// Patch existing nodes so images, focus, disclosure state and animations do not restart.
function patch(node,next){
 if(node.nodeType!==next.nodeType||node.nodeName!==next.nodeName){node.replaceWith(next.cloneNode(true));return;}
 if(node.nodeType===Node.TEXT_NODE){if(node.data!==next.data)node.data=next.data;return;}
 if(node.nodeType!==Node.ELEMENT_NODE)return;
 for(const a of [...node.attributes])if(!next.hasAttribute(a.name)&&!(node.tagName==='DETAILS'&&a.name==='open'))node.removeAttribute(a.name);
 for(const a of next.attributes)if(!(node.tagName==='DETAILS'&&a.name==='open')&&node.getAttribute(a.name)!==a.value)node.setAttribute(a.name,a.value);
 const children=[...node.childNodes],incoming=[...next.childNodes];
 incoming.forEach((child,i)=>children[i]?patch(children[i],child):node.append(child.cloneNode(true)));
 children.slice(incoming.length).forEach(child=>child.remove());
}
export function replace(node,html){if(node._renderedHTML===html)return;const next=document.createElement('div');next.innerHTML=html;const children=[...node.childNodes];[...next.childNodes].forEach((child,i)=>children[i]?patch(children[i],child):node.append(child.cloneNode(true)));children.slice(next.childNodes.length).forEach(child=>child.remove());node._renderedHTML=html;}
export function renderProgress(p){const flow=document.querySelector('.flow-track')?.parentElement;if(!flow||!p)return;let node=flow.querySelector('#evidence-progress');if(!node){node=document.createElement('section');node.id='evidence-progress';node.setAttribute('aria-label','六阶段证据进度');flow.append(node);}replace(node,progress(p));}

function usage(d){const coverage=d.coverage;return `<div class="section-head"><div><p class="eyebrow">03 / DAILY USAGE</p><h2>每日用量</h2><p class="muted">看清团队每天使用的 token，保留记录的边界。</p></div><span class="quality-badge">${esc(d.quality||'UNAVAILABLE')}</span></div><div class="usage-quality"><div><span class="metric-label">本机日志可读覆盖率</span><strong>${coverage?.percent??'未知'}${coverage?.percent==null?'':'%'}</strong><span>${coverage?.readable_threads??'?'} / ${coverage?.discovered_threads??'?'} 个项目会话</span></div><p>${d.quality==='LOCAL_EXACT'?'LOCAL_EXACT 表示已读取日志中的精确增量，不能代表所有调用均已记录。':'当前无法提供完整的本机精确统计。'}<br>覆盖率只衡量日志可读比例，<strong>不是账号覆盖率或统计准确率</strong>。未覆盖、在途调用和其他设备不计入。</p></div><p class="source">开始统计：${fmt(d.started_at)} · 更新：${fmt(d.updated_at)}<br>北京时间 · 启用前不回填 · 排除计数异常 ${coverage?.excluded_counter_anomalies??'未知'} 次</p>${d.error?`<p role="status" class="bridge-note">${esc(d.error)}</p>`:''}<div class="usage-days">${(d.days||[]).map((day,index)=>`<details class="usage-day" data-key="day-${esc(day.date)}" ${index===0?'open':''}><summary><span>${esc(day.date)}<small>已记录日总量</small></span><strong>${num(day.total_tokens)} <small>token</small></strong></summary><div class="usage-rows">${day.roles.map(r=>`<div class="usage-role ${r.total_tokens===null?'uncovered':''}"><span>${esc(r.role)}${r.total_tokens===null?'<small>日志未覆盖，不能按 0 计算</small>':String(r.role).includes('未归属')?'<small>未匹配中央角色路由</small>':''}</span><strong>${num(r.total_tokens)}<small>${r.total_tokens===null?'':'token'}</small></strong></div>`).join('')}</div></details>`).join('')||'<p class="empty-preview">尚无可展示的日记录，不能据此认定没有消耗。</p>'}</div><details class="method-details" data-key="method"><summary>计算方法、来源与未覆盖范围</summary><p>${esc(d.method)}</p><p>${esc(d.limitations)}</p><p>${esc(d.scope)}</p><p>0 仅表示启用后未观测到增量；“未覆盖”表示记录不足。“未归属”保留原线程统计，不强行分配给员工。</p><p class="source">来源：${(d.sources||[]).map(esc).join('；')}</p></details>`;}
function progress(p){return `<div class="delivery-progress"><h2>本轮部门交付 · ${(p.deliveries||[]).filter(d=>d.reports.length).length} / ${(p.deliveries||[]).length}</h2><p class="muted">有报告即可显示；已交付不等于通过审核或完成后续任务。</p>${(p.deliveries||[]).map(d=>`<details data-key="delivery-${esc(d.thread_id)}"><summary>${esc(d.role)} · ${d.reports.length?'已有交付':'等待交付文件'}</summary>${d.reports.map(f=>`<p><strong>${esc(f.name)}</strong><br>${esc(f.summary)}<br><span class="source">${esc(f.path)} · ${fmt(f.updated_at)}</span></p>`).join('')}</details>`).join('')}</div>${p.sync_note?`<p class="bridge-note">${esc(p.sync_note)}</p>`:''}<div class="evidence-heading">${ring(p.percent,'总证据进度')}<div><p class="eyebrow">EVIDENCE / VERIFIED CHECKPOINTS</p><h2>证据进度 ${p.percent}%</h2><p class="muted">每一步都有依据。完成的检查点才计入进度。</p><p class="source">证据更新：${fmt(p.updated_at)}<br>每 3 秒自动同步已保存的交付 · 100% 表示准备检查点完成，不代表已发布</p></div></div><div class="checkpoint-grid">${p.stages.map((s,i)=>`<details class="checkpoint-stage" data-key="stage-${i}" ${s.percent<100?'open':''}><summary><span class="stage-number">${String(i+1).padStart(2,'0')}</span><span>${esc(s.label)}<small>总进度权重 ${s.weight}%</small></span><strong>${s.percent}%<small>阶段内</small></strong><progress max="100" value="${percent(s.percent)}" aria-label="${esc(s.label)}阶段内完成度"></progress></summary><div class="checkpoint-list">${s.checkpoints.map(c=>`<div class="checkpoint ${c.complete?'complete':''}"><span class="checkpoint-icon" aria-hidden="true">${c.complete?'✓':'○'}</span><div><strong>${c.complete?'已完成':'未完成'} · ${esc(c.label)}</strong><small>计入总进度 ${c.weight}%</small><p class="source">${c.complete?'来源：'+c.sources.map(esc).join('<br>'):esc(c.reason)}</p></div></div>`).join('')}</div></details>`).join('')}</div><details class="method-details" data-key="progress-method"><summary>进度口径与依据</summary><p class="source">${esc(p.method)}</p><p class="source">检查点与来源由数据接口提供；动画只表现读到的状态，不随时间增加百分比。</p></details>`;}
let busy=false,rerun=false,usageNeedsScroll=location.hash==='#usage';window.addEventListener('hashchange',()=>{usageNeedsScroll=location.hash==='#usage';});
async function update(){if(busy){rerun=true;return;}busy=true;try{
 const agents=document.querySelector('#agents');let inserted=false;if(agents&&!document.querySelector('#usage-panel')){agents.insertAdjacentHTML('afterend','<section id="usage-panel" aria-labelledby="usage-heading"><h2 id="usage-heading">每日用量</h2><p class="source">正在读取本机记录…</p></section>');inserted=true;}
 const panel=document.querySelector('#usage-panel');if(panel){try{const response=await fetch('/api/v1/workbench/usage');if(!response.ok)throw Error();const d=await response.json();if(panel.isConnected){replace(panel,usage(d));panel.querySelector('h2').id='usage-heading';if(inserted&&usageNeedsScroll&&location.hash==='#usage'){panel.scrollIntoView();usageNeedsScroll=false;}}}catch{if(panel.isConnected)panel.innerHTML='<h2 id="usage-heading">每日用量</h2><p role="status">读取失败，当前用量未知。稍后自动重试。</p>';}}

 }finally{busy=false;if(rerun){rerun=false;queueMicrotask(update);}}}
new MutationObserver(()=>update()).observe(document.querySelector('#view'),{childList:true});setInterval(update,30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)update();});update();
